# Generated by Django 3.2.9 on 2021-11-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='body',
        ),
    ]
