# Generated by Django 3.2.9 on 2021-11-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='d_followings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dorm_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='s_followings',
        ),
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.CharField(choices=[('당뇨병', '당뇨병')], default='', max_length=50),
        ),
    ]
