# Generated by Django 3.2.9 on 2021-11-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211108_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_dorm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_id',
        ),
    ]
