# Generated by Django 3.2.9 on 2021-11-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211108_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disease',
            field=models.CharField(choices=[('당뇨병', '당뇨병'), ('고혈압', '고혈압')], default='', max_length=50),
        ),
    ]
